### ISSUE TITLE
Event loop closed exception on every other request

### ISSUE THREAD

**Issue by tommoyer** [gilesknap/maaspower#34]
There is odd behavior when running maaspower. Every other request fails with the following stacktrace. I tested this on Ubuntu 22.04 and Ubuntu 24.04. I also tested the package from PyPI and the latest commit from git with the same behavior.

```
Traceback (most recent call last):
  File "/root/.local/share/pipx/venvs/maaspower/lib/python3.12/site-packages/kasa/xortransport.py", line 163, in send
    return await self._execute_send(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.local/share/pipx/venvs/maaspower/lib/python3.12/site-packages/kasa/xortransport.py", line 85, in _execute_send
    packed_block_size = await self.reader.readexactly(self.BLOCK_SIZE)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/streams.py", line 752, in readexactly
    await self._wait_for_data('readexactly')
  File "/usr/lib/python3.12/asyncio/streams.py", line 545, in _wait_for_data
    await self._waiter
RuntimeError: Task <Task pending name='Task-4' coro=<KasaDevice._query_state() running at /root/.local/share/pipx/venvs/maaspower/lib/python3.12/site-packages/maaspower/devices/kasa_device.py:73> cb=[_run_until_complete_cb() at /usr/lib/python3.12/asyncio/base_events.py:182]> got Future <Future pending> attached to a different loop

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/.local/share/pipx/venvs/maaspower/lib/python3.12/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.local/share/pipx/venvs/maaspower/lib/python3.12/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.local/share/pipx/venvs/maaspower/lib/python3.12/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.local/share/pipx/venvs/maaspower/lib/python3.12/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.local/share/pipx/venvs/maaspower/lib/python3.12/site-packages/flask_basicauth.py", line 108, in wrapper
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.local/share/pipx/venvs/maaspower/lib/python3.12/site-packages/maaspower/webhook.py", line 35, in command
    result = device.do_command(command)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.local/share/pipx/venvs/maaspower/lib/python3.12/site-packages/maaspower/maasconfig.py", line 97, in do_command
    return self.query_state()
           ^^^^^^^^^^^^^^^^^^
  File "/root/.local/share/pipx/venvs/maaspower/lib/python3.12/site-packages/maaspower/devices/kasa_device.py", line 67, in query_state
    return asyncio.run(self._query_state())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/root/.local/share/pipx/venvs/maaspower/lib/python3.12/site-packages/maaspower/devices/kasa_device.py", line 73, in _query_state
    await self.plug.update()
  File "/root/.local/share/pipx/venvs/maaspower/lib/python3.12/site-packages/kasa/iot/iotdevice.py", line 295, in update
    await self._modular_update(req)
  File "/root/.local/share/pipx/venvs/maaspower/lib/python3.12/site-packages/kasa/iot/iotdevice.py", line 389, in _modular_update
    await self.protocol.query(request) for request in request_list if request
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.local/share/pipx/venvs/maaspower/lib/python3.12/site-packages/kasa/iotprotocol.py", line 63, in query
    return await self._query(request, retry_count)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.local/share/pipx/venvs/maaspower/lib/python3.12/site-packages/kasa/iotprotocol.py", line 68, in _query
    return await self._execute_query(request, retry)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.local/share/pipx/venvs/maaspower/lib/python3.12/site-packages/kasa/iotprotocol.py", line 114, in _execute_query
    resp = await self._transport.send(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.local/share/pipx/venvs/maaspower/lib/python3.12/site-packages/kasa/xortransport.py", line 165, in send
    await self.reset()
  File "/root/.local/share/pipx/venvs/maaspower/lib/python3.12/site-packages/kasa/xortransport.py", line 116, in reset
    await self.close()
  File "/root/.local/share/pipx/venvs/maaspower/lib/python3.12/site-packages/kasa/xortransport.py", line 99, in close
    self.close_without_wait()
  File "/root/.local/share/pipx/venvs/maaspower/lib/python3.12/site-packages/kasa/xortransport.py", line 109, in close_without_wait
    writer.close()
  File "/usr/lib/python3.12/asyncio/streams.py", line 358, in close
    return self._transport.close()
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/selector_events.py", line 1210, in close
    super().close()
  File "/usr/lib/python3.12/asyncio/selector_events.py", line 875, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "/usr/lib/python3.12/asyncio/base_events.py", line 795, in call_soon
    self._check_closed()
  File "/usr/lib/python3.12/asyncio/base_events.py", line 541, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
10.10.10.112 - - [30/Sep/2024 02:35:40] "GET /maaspower/meer8-0/query HTTP/1.1" 500 -
```

**Comment by gilesknap** [comment]
Can you give a little more background please?
What does your config look like?

**Comment by tommoyer** [comment]
Sorry. I should have included that. I have a relatively simple setup with three TP-Link Kasa plugs being controlled by maaspower.

```
# yaml-language-server: $schema=maaspower.schema.json
# NOTE: above relative path to a schema file from 'maaspower schema <filename>'

name: MAAS power control webhooks
ip_address: 0.0.0.0
port: 5000
username: maaspower
password: maaspower

devices:
  - type: KasaDevice
    name: meer8-0
    ip_address: 10.10.10.61
  - type: KasaDevice
    name: meer8-1
    ip_address: 10.10.10.62
  - type: KasaDevice
    name: meer8-2
    ip_address: 10.10.10.63
```

MAAS is on an isolated network to avoid collisions with my LAN DNS/DHCP services for my other machines. In one test, MAAS was running on a bare-metal system (24.04) and the other was in a LXD container (22.04) with identical results. The first request works, then the second fails. The stack trace is always the same but maaspower keeps running and the third request works, with the fourth failing. I've tested this with `query`, `on`, and `off`. The specific request does not seem to matter.

**Comment by gilesknap** [comment]
Hmm, I did not write the Kasa support, neither have I been able to test it. So not sure I can be much help here.
@lbunge have you seen this issue at all? Thanks.

**Comment by tommoyer** [comment]
I can try running the Kasa code outside of the maaspower loop to see if that is where the problem is. I'll also check if I have other devices that are not Kasa that I could test with too.

**Comment by tommoyer** [comment]
Quick update. I wrote a small python script that just uses the asyncio and kasa libraries to isolate the issue. I think this is something wrong with python-kasa, not maaspower. I'm going to report an issue there and then if the devs provide a fix, I will submit a PR fixing the code in the kasa_device.py.

**Comment by tommoyer** [comment]
PR submitted: https://github.com/gilesknap/maaspower/pull/35

I've tested this on my local setup and was able to run multiple commands against Kasa devices without any exceptions being thrown.

**Comment by gilesknap** [comment]
awesome!
